Javascript. Task 01 (additional).
metacorn/javascript pull request #4
Opened 2020-05-16 16:58 UTC by metacorn

2020-05-16 18:28 UTC, arswarog requested changes

2020-05-16 18:28 UTC, arswarog commented on 02_time_formatting.js
> +}
проверь еще раз на исходных данных. в коде опечатка и неверная работа с некоторыми занчениями

2020-05-16 18:28 UTC, arswarog commented on 04_decoder.js
> +    result += (letter_index >= 0 && letter_index <= 25) ? String.fromCharCode(letter_index + keyCodeA) : input[index];
```js
result += (letter_index >= 0 && letter_index <= 25) 
   ? String.fromCharCode(letter_index + keyCodeA)
   : input[index];```
Будет читаться лучше

2020-05-16 23:51 UTC, metacorn commented on 02_time_formatting.js
> +}
ага, исправил.

2020-05-16 23:51 UTC, metacorn commented on 04_decoder.js
> +    result += (letter_index >= 0 && letter_index <= 25) ? String.fromCharCode(letter_index + keyCodeA) : input[index];
согласен) исправил.

2020-05-17 16:57 UTC, arswarog requested changes

2020-05-17 16:57 UTC, arswarog commented on 02_time_formatting.js
> +}
Некорректно отрабатывают. например такие входные данные
12:40 pm
12:00 am

2020-05-17 23:39 UTC, closed without merging